name: Deploy Documentation

on: 
  release:
    types:
      - prereleased

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
    - uses: actions/checkout@v2
      
    - name: Setup Python      
      uses: actions/setup-python@v1.2.0
      with:
        python-version: '3.8.x'
        architecture: 'x64'
      
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3

    - name: Install requirements
      run: poetry install

    - name: Deploy
      run: poetry run mkdocs gh-deploy
